---
spring:
  jpa:
    open-in-view: "false"
    properties:
      hibernate:
        "[default_schema]": dbo
        "[format_sql]": true
        "[show_sql]": true
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: "true"
  jackson:
    time-zone: EST
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=false;databaseName=LMS;trustServerCertificate=true;integratedSecurity=true
    #username: null
    #password: null
  profiles:
    active: development
logging:
  level:
    org:
      springframework:
        web: info
      apache: info
      hibernate:
        type:
          descriptor:
            sql: trace
  config: src/main/resources/log4j2.properties
